/**
 * Responsive image delivery. Local /img/* files have WebP variants generated by
 * scripts/optimize-images.mjs (see the manifest); Cloudinary URLs (uploaded via
 * the /admin backoffice) get on-the-fly f_auto/q_auto transforms. The original
 * src always stays as fallback, so a missing variant can never break a page.
 */
import manifest from "./img-manifest.json";

type Entry = { w: number[]; ar: number };
const M = manifest as Record<string, Entry>;
const CLOUDINARY = /^(https:\/\/res\.cloudinary\.com\/[^/]+\/image\/upload\/)(?!\w+_)(.+)$/;
const CLOUD_WIDTHS = [480, 960, 1440];

const optBase = (src: string) => "/img/opt/" + src.slice("/img/".length).replace(/\.[a-z]+$/i, "");

/**
 * Cloudinary transform. Without `ar`: only capped in width (c_limit).
 * With `ar` (ex. "4:5"): recadrée serveur au ratio du slot avec g_auto —
 * le cadrage IA garde le sujet (visage, action) dans l'image au lieu d'un
 * crop centre aveugle. L'admin peut donc uploader N'IMPORTE quelle photo.
 */
const cloudT = (w: number, ar?: string) =>
  ar ? `f_auto,q_auto,c_fill,g_auto,ar_${ar},w_${w}` : `f_auto,q_auto,c_limit,w_${w}`;

/** srcset string for an image path/URL — "" when no variants are available. */
export function srcsetOf(src: string, ar?: string): string {
  const e = M[src];
  if (e) return e.w.map((w) => `${optBase(src)}-${w}.webp ${w}w`).join(", ");
  const c = src.match(CLOUDINARY);
  if (c) return CLOUD_WIDTHS.map((w) => `${c[1]}${cloudT(w, ar)}/${c[2]} ${w}w`).join(", ");
  return "";
}

/** Single best URL for a target display width (CSS backgrounds). */
export function optUrl(src: string, target = 960, ar?: string): string {
  const e = M[src];
  if (e) {
    const w = e.w.find((x) => x >= target) ?? e.w[e.w.length - 1];
    return `${optBase(src)}-${w}.webp`;
  }
  const c = src.match(CLOUDINARY);
  if (c) return `${c[1]}${cloudT(target, ar)}/${c[2]}`;
  return src;
}

/** src + srcset + sizes attribute chunk for an <img> template literal. */
export function imgAttrs(src: string, sizes: string, ar?: string): string {
  const ss = srcsetOf(src, ar);
  return ss ? `src="${src}" srcset="${ss}" sizes="${sizes}"` : `src="${src}"`;
}

/**
 * Section backgrounds are declared as <div class="sec-bg" data-bg="/img/x.jpg">
 * instead of an inline background-image, so the bytes are only fetched when the
 * section approaches the viewport (a CSS background offers no native lazy path).
 */
export function initLazyBackgrounds(): void {
  const els = document.querySelectorAll<HTMLElement>("[data-bg]");
  if (!els.length) return;
  const target = window.innerWidth > 1024 ? 1440 : 960;
  const apply = (el: HTMLElement) => {
    const src = el.dataset.bg;
    if (!src) return;
    el.style.setProperty("--img", `url("${optUrl(src, target)}")`);
    delete el.dataset.bg;
  };
  if (!("IntersectionObserver" in window)) {
    els.forEach(apply);
    return;
  }
  const io = new IntersectionObserver(
    (entries) => {
      for (const en of entries) {
        if (en.isIntersecting) {
          io.unobserve(en.target);
          apply(en.target as HTMLElement);
        }
      }
    },
    { rootMargin: "600px" }
  );
  els.forEach((el) => io.observe(el));
}
